logging:
        file: ${user.dir}/log/marketdataservice.log
        level:
            org.apache: ERROR
            org.hibernate: ERROR

debug: false

server:
    port: 5530

# prevents that a date is serialized as a timestamp, which is the default
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

---
spring:
    profiles: production
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/marketdataservice
        username: postgres
        password: stepae02
        initialize: false
    jpa:
        show-sql: false
---
spring:
    profiles: development
    datasource:
        url: jdbc:postgresql://localhost:5432/marketdataservice
        username: postgres
        password: stepae02
        initialize: true
        data: file:${user.dir}/sqlscripts/domain-${spring.datasource.platform}.sql, file:${user.dir}/sqlscripts/mds.sql
        driver-class-name: org.postgresql.Driver
        platform: postgresql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            javax.persistence.schema-generation.create-database-schemas: true
            org.hibernate.envers.revision_field_name: RevisionId
            org.hibernate.envers.revision_type_field_name : RevisionType
            org.hibernate.envers.revision_on_collection_change: false
            hibernate.id.new_generator_mappings: true
---
debug: false
spring:
    profiles: test
    datasource:
        data: file:${user.dir}/sqlscripts/domain-${spring.datasource.platform}.sql, file:${user.dir}/sqlscripts/mds.sql
        platform: derby
        initialize: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            org.hibernate.envers.revision_field_name: RevisionId
            org.hibernate.envers.revision_type_field_name : RevisionType
            org.hibernate.envers.revision_on_collection_change: false
            hibernate.id.new_generator_mappings: true
---
